
import React, { useState } from 'react';
import { Card, Button, Input } from '../components/Shared';
import { BookOpen, Search, Printer, FileText } from 'lucide-react';
import { generateAnalysis } from '../services/geminiService';
import ReactMarkdown from 'react-markdown';
import { useLanguage } from '../App';
import { I18N } from '../constants';

export const Library = () => {
    const { language } = useLanguage();
    const t = I18N[language];
    const [query, setQuery] = useState('');
    const [content, setContent] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);

    const handleSearch = async () => {
        if (!query) return;
        setLoading(true);
        try {
            const prompt = `Role: Medical Educator.
            Task: Create a patient education handout for "${query}".
            Audience: Layperson (6th-grade reading level).
            Sections: What is it?, Symptoms, Home Care, When to call a doctor.
            Format: Markdown.`;
            const res = await generateAnalysis(prompt, language);
            setContent(res);
        } catch(e) { setContent("Could not retrieve article."); }
        setLoading(false);
    };

    return (
        <div className="max-w-5xl mx-auto h-full flex flex-col">
            <div className="flex justify-between items-center mb-8 no-print">
                <div className="flex items-center gap-3">
                    <BookOpen className="text-blue-400 h-8 w-8" />
                    <div>
                        <h1 className="text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-indigo-500">{t.library.title}</h1>
                        <p className="text-textSecondary text-sm">{t.library.subtitle}</p>
                    </div>
                </div>
                {content && (
                    <Button variant="secondary" onClick={() => window.print()}>
                        <Printer size={18} className="mr-2" /> {t.common.exportPdf}
                    </Button>
                )}
            </div>

            <div className="flex-1 flex flex-col gap-6">
                <div className="bg-surface/50 p-6 rounded-3xl border border-white/5 no-print">
                    <div className="flex gap-4">
                        <div className="flex-1">
                            <Input 
                                placeholder={t.library.searchPlaceholder}
                                value={query}
                                onChange={(e) => setQuery(e.target.value)}
                                enableVoice
                                onVoiceInput={setQuery}
                                className="bg-surfaceHighlight"
                            />
                        </div>
                        <Button onClick={handleSearch} isLoading={loading} disabled={!query}>
                            <Search size={18} className="mr-2" /> {t.library.find}
                        </Button>
                    </div>
                </div>

                <div className="flex-1 bg-white text-black p-8 md:p-12 rounded-3xl overflow-y-auto shadow-2xl print:shadow-none print:p-0 print:overflow-visible">
                    {!content ? (
                        <div className="h-full flex flex-col items-center justify-center text-gray-400 opacity-50">
                            <FileText size={64} className="mb-4" />
                            <p className="text-lg font-bold uppercase tracking-widest">{t.common.welcome}</p>
                        </div>
                    ) : (
                        <article className="prose prose-lg max-w-none prose-headings:font-bold prose-headings:text-blue-900 prose-p:text-gray-700">
                             <div className="mb-8 pb-4 border-b border-gray-200 flex justify-between items-center">
                                <h1 className="text-4xl font-black text-black m-0 capitalize">{query}</h1>
                                <div className="hidden print:block text-xs text-gray-500">Generated by Asclepius AI</div>
                             </div>
                             <ReactMarkdown>{content}</ReactMarkdown>
                             
                             <div className="mt-12 pt-8 border-t border-gray-200 text-center text-xs text-gray-500">
                                 <p>Disclaimer: This information is for educational purposes only and does not constitute medical advice. Always consult a healthcare professional.</p>
                             </div>
                        </article>
                    )}
                </div>
            </div>
        </div>
    );
};
